name: Generate Source Tarball

# Run on demand only
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to package (e.g. release_0_9_14)'
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: ${{ inputs.tag }}

    - name: archive
      id: archive
      run: |
        THISDIR="$PWD"
        cd desmume/src/frontend/posix
        autoreconf -i
        cd "$THISDIR"
        VERSION=$(printf "%s\n" '${{ inputs.tag }}' | sed -e 's/^release_//' -e 's/_/./g')
        PKGNAME="desmume-$VERSION"
        mkdir -p /tmp/$PKGNAME
        mv * /tmp/$PKGNAME
        mv /tmp/$PKGNAME .
        TARBALL=$PKGNAME.tar.xz
        tar cJf $TARBALL $PKGNAME
        echo "tarball=$TARBALL" >> "$GITHUB_OUTPUT"

    - name: upload tarball
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload '${{ inputs.tag }}' './${{ steps.archive.outputs.tarball }}' --clobber
